### ISSUE TITLE
--detach==true cannot be handled correctly

### ISSUE THREAD

**Issue by reconman** [bucherfa/docker-compose-converter#3]
The conversion handles `-d` fine, but not `--detach=true`, which is the same thing.

Here's a test command: `docker run --detach=true -v nextcloud:/var/www/html nextcloud`.

The current result is:
```
version: '3'
services:
  nextcloud:
    image: nextcloud
    volumes:
      - 'nextcloud:/var/www/html'
    command: '--detach=true'
```
